### ISSUE TITLE
what is your yolo version?

### ISSUE THREAD

**Issue by ghost** [ussvarma/Count-cars-and-trucks#1]
thanks for your great project.
i have a question, 
which  yolov5 version do you use? version 6.1 or 6.2?

i have a traffic vedio from UAV. so how to draw lines  at each road intersection?

i can send this vedio if you want to test.

thanks a lot!!!!

![image](https://user-images.githubusercontent.com/110151053/196583807-02a7e4f8-ac01-4401-af88-0a738f62de70.png)

**Comment by ussvarma** [comment]
I used yolov5. Also to draw lines use opencv function cv2.line()

**Comment by ussvarma** [comment]
> thanks for your great project. i have a question, which yolov5 version do you use? version 6.1 or 6.2?
> 
> i have a traffic vedio from UAV. so how to draw lines at each road intersection?
> 
> i can send this vedio if you want to test.
> 
> thanks a lot!!!!
> 
> ![image](https://user-images.githubusercontent.com/110151053/196583807-02a7e4f8-ac01-4401-af88-0a738f62de70.png)

I used yolov5. Also to draw lines use opencv function cv2.line()
